$("document").ready(function(){
    $("#inform").click(function(){
        $(".detali").slideToggle();
    });
    $("#summ").click(function(){
        $(".persSum").slideToggle();
    });
    $("#education").click(function(){
        $(".edu-detalis").slideToggle();
    });
    $("#training").click(function(){
        $(".train-deta").slideToggle();
    });
    $("#tickinckal").click(function(){
        $(".tickinickal-skils").slideToggle();
    });
    $("#pers").click(function(){
        $(".pers-skils").slideToggle();
    });
    $("#project").click(function(){
        $(".proj1").slideToggle();
    });
    
});